"""REGOS API schemas."""
# Generated from REGOS public Swagger by tools/generate_regos_public_api.py.

from __future__ import annotations

from datetime import datetime as _DateTime
from decimal import Decimal as _Decimal
from enum import Enum, IntEnum
from typing import Any, TypeAlias

from pydantic import ConfigDict, Field as PydField, RootModel

from schemas.api.common.base import RegosModel


class StringRegosArrayResult(RegosModel):
    "OpenAPI-only typed equivalent of SingleArrayResult."
    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    ok: bool | None = PydField(default=None, description="Признак успешности выполнения запроса.")
    result: list[str] | Error | None = PydField(default=None, description="Массив результата.")


class WebHookActionsEnum(str, Enum):
    "Перечисление действий для WebHook"
    Default = "Default"
    PromoBonusPaymentPerformed = "PromoBonusPaymentPerformed"
    PromoBonusEnrollmentPerformed = "PromoBonusEnrollmentPerformed"
    PromoBonusPaymentCanceled = "PromoBonusPaymentCanceled"
    PromoBonusManualIncomeOperationCreated = "PromoBonusManualIncomeOperationCreated"
    PromoBonusManualOutcomeOperationCreated = "PromoBonusManualOutcomeOperationCreated"
    DocSessionOpened = "DocSessionOpened"
    DocSessionClosed = "DocSessionClosed"
    DocChequeClosed = "DocChequeClosed"
    DocChequeCanceled = "DocChequeCanceled"
    POSChequePayDebt = "POSChequePayDebt"
    DocOrderDeliveryAdded = "DocOrderDeliveryAdded"
    DocOrderDeliveryEdited = "DocOrderDeliveryEdited"
    DocOrderDeliveryDeleted = "DocOrderDeliveryDeleted"
    DocOrderDeliveryPerformed = "DocOrderDeliveryPerformed"
    DocOrderDeliveryPerformCanceled = "DocOrderDeliveryPerformCanceled"
    DocOrderDeliveryStatusSet = "DocOrderDeliveryStatusSet"
    DocOrderDeliveryStockSet = "DocOrderDeliveryStockSet"
    DocOrderDeliveryCourierSet = "DocOrderDeliveryCourierSet"
    DocOrderDeliveryReturned = "DocOrderDeliveryReturned"
    DocOrderDeliveryActualized = "DocOrderDeliveryActualized"
    DocOrderDeliveryDeleteMarked = "DocOrderDeliveryDeleteMarked"
    DocOrderDeliveryFiscalInfoSet = "DocOrderDeliveryFiscalInfoSet"
    DocOrderDeliveryResetToBeginning = "DocOrderDeliveryResetToBeginning"
    DocWholeSaleAdded = "DocWholeSaleAdded"
    DocWholeSaleEdited = "DocWholeSaleEdited"
    DocWholeSaleDeleteMarked = "DocWholeSaleDeleteMarked"
    DocWholeSaleDeleted = "DocWholeSaleDeleted"
    DocWholeSalePerformed = "DocWholeSalePerformed"
    DocWholeSalePerformCanceled = "DocWholeSalePerformCanceled"
    DocWholeSaleReturnAdded = "DocWholeSaleReturnAdded"
    DocWholeSaleReturnEdited = "DocWholeSaleReturnEdited"
    DocWholeSaleReturnDeleteMarked = "DocWholeSaleReturnDeleteMarked"
    DocWholeSaleReturnDeleted = "DocWholeSaleReturnDeleted"
    DocWholeSaleReturnPerformed = "DocWholeSaleReturnPerformed"
    DocWholeSaleReturnPerformCanceled = "DocWholeSaleReturnPerformCanceled"
    DocOrderFromPartnerAdded = "DocOrderFromPartnerAdded"
    DocOrderFromPartnerEdited = "DocOrderFromPartnerEdited"
    DocOrderFromPartnerDeleteMarked = "DocOrderFromPartnerDeleteMarked"
    DocOrderFromPartnerDeleted = "DocOrderFromPartnerDeleted"
    DocOrderToMovementAdded = "DocOrderToMovementAdded"
    DocOrderToMovementEdited = "DocOrderToMovementEdited"
    DocOrderToMovementDeleteMarked = "DocOrderToMovementDeleteMarked"
    DocOrderToMovementDeleted = "DocOrderToMovementDeleted"
    DocOrderToPartnerAdded = "DocOrderToPartnerAdded"
    DocOrderToPartnerEdited = "DocOrderToPartnerEdited"
    DocOrderToPartnerDeleteMarked = "DocOrderToPartnerDeleteMarked"
    DocOrderToPartnerDeleted = "DocOrderToPartnerDeleted"
    DocPurchaseAdded = "DocPurchaseAdded"
    DocPurchaseEdited = "DocPurchaseEdited"
    DocPurchaseDeleteMarked = "DocPurchaseDeleteMarked"
    DocPurchaseDeleted = "DocPurchaseDeleted"
    DocPurchasePerformed = "DocPurchasePerformed"
    DocPurchasePerformCanceled = "DocPurchasePerformCanceled"
    DocReturnsToPartnerAdded = "DocReturnsToPartnerAdded"
    DocReturnsToPartnerEdited = "DocReturnsToPartnerEdited"
    DocReturnsToPartnerDeleteMarked = "DocReturnsToPartnerDeleteMarked"
    DocReturnsToPartnerDeleted = "DocReturnsToPartnerDeleted"
    DocReturnsToPartnerPerformed = "DocReturnsToPartnerPerformed"
    DocReturnsToPartnerPerformCanceled = "DocReturnsToPartnerPerformCanceled"
    DocMovementAdded = "DocMovementAdded"
    DocMovementEdited = "DocMovementEdited"
    DocMovementDeleteMarked = "DocMovementDeleteMarked"
    DocMovementDeleted = "DocMovementDeleted"
    DocMovementPerformed = "DocMovementPerformed"
    DocMovementPerformCanceled = "DocMovementPerformCanceled"
    DocInventoryAdded = "DocInventoryAdded"
    DocInventoryEdited = "DocInventoryEdited"
    DocInventoryDeleteMarked = "DocInventoryDeleteMarked"
    DocInventoryDeleted = "DocInventoryDeleted"
    DocInventoryClosed = "DocInventoryClosed"
    DocInventoryOpened = "DocInventoryOpened"
    DocInOutAdded = "DocInOutAdded"
    DocInOutEdited = "DocInOutEdited"
    DocInOutDeleteMarked = "DocInOutDeleteMarked"
    DocInOutDeleted = "DocInOutDeleted"
    DocInOutPerformed = "DocInOutPerformed"
    DocInOutPerformCanceled = "DocInOutPerformCanceled"
    CampaignAdded = "CampaignAdded"
    CampaignRecipientsStatusSet = "CampaignRecipientsStatusSet"
    CampaignDeleted = "CampaignDeleted"
    SMSAdded = "SMSAdded"
    SMSStatusSet = "SMSStatusSet"
    DocPaymentAdded = "DocPaymentAdded"
    DocPaymentEdited = "DocPaymentEdited"
    DocPaymentDeleteMarked = "DocPaymentDeleteMarked"
    DocPaymentDeleted = "DocPaymentDeleted"
    DocPaymentPerformed = "DocPaymentPerformed"
    DocPaymentPerformCanceled = "DocPaymentPerformCanceled"
    RetailCustomerAdded = "RetailCustomerAdded"
    RetailCustomerEdited = "RetailCustomerEdited"
    RetailCustomerDeleteMarked = "RetailCustomerDeleteMarked"
    RetailCustomerDeleted = "RetailCustomerDeleted"
    RetailCardAdded = "RetailCardAdded"
    RetailCardEdited = "RetailCardEdited"
    RetailCardDeleted = "RetailCardDeleted"
    PartnerAdded = "PartnerAdded"
    PartnerEdited = "PartnerEdited"
    PartnerDeleteMarked = "PartnerDeleteMarked"
    PartnerDeleted = "PartnerDeleted"
    ItemAdded = "ItemAdded"
    ItemEdited = "ItemEdited"
    ItemDeleteMarked = "ItemDeleteMarked"
    ItemDeleted = "ItemDeleted"
    DocAccountMovementAdded = "DocAccountMovementAdded"
    DocAccountMovementEdited = "DocAccountMovementEdited"
    DocAccountMovementDeleteMarked = "DocAccountMovementDeleteMarked"
    DocAccountMovementDeleted = "DocAccountMovementDeleted"
    DocAccountMovementPerformed = "DocAccountMovementPerformed"
    DocAccountMovementPerformCanceled = "DocAccountMovementPerformCanceled"
    UserAdded = "UserAdded"
    UserAddedGlobal = "UserAddedGlobal"
    UserEdited = "UserEdited"
    UserDeleted = "UserDeleted"
    ItemGroupAdded = "ItemGroupAdded"
    ItemGroupEdited = "ItemGroupEdited"
    ItemGroupDeleted = "ItemGroupDeleted"
    DepartmentAdded = "DepartmentAdded"
    DepartmentEdited = "DepartmentEdited"
    DepartmentDeleted = "DepartmentDeleted"
    UnitAdded = "UnitAdded"
    UnitEdited = "UnitEdited"
    UnitDeleted = "UnitDeleted"
    SizeChartAdded = "SizeChartAdded"
    SizeChartEdited = "SizeChartEdited"
    SizeChartDeleted = "SizeChartDeleted"
    ColorAdded = "ColorAdded"
    ColorEdited = "ColorEdited"
    ColorDeleted = "ColorDeleted"
    BrandAdded = "BrandAdded"
    BrandEdited = "BrandEdited"
    BrandDeleted = "BrandDeleted"
    ProducerAdded = "ProducerAdded"
    ProducerEdited = "ProducerEdited"
    ProducerDeleted = "ProducerDeleted"
    CountryAdded = "CountryAdded"
    CountryEdited = "CountryEdited"
    CountryDeleted = "CountryDeleted"
    PartnerGroupAdded = "PartnerGroupAdded"
    PartnerGroupEdited = "PartnerGroupEdited"
    PartnerGroupDeleted = "PartnerGroupDeleted"
    RetailCustomerGroupAdded = "RetailCustomerGroupAdded"
    RetailCustomerGroupEdited = "RetailCustomerGroupEdited"
    RetailCustomerGroupDeleted = "RetailCustomerGroupDeleted"
    RetailReturnReasonAdded = "RetailReturnReasonAdded"
    RetailReturnReasonEdited = "RetailReturnReasonEdited"
    RetailReturnReasonDeleted = "RetailReturnReasonDeleted"
    DeliveryFromAdded = "DeliveryFromAdded"
    DeliveryFromEdited = "DeliveryFromEdited"
    DeliveryFromDeleted = "DeliveryFromDeleted"
    DeliveryTypeAdded = "DeliveryTypeAdded"
    DeliveryTypeEdited = "DeliveryTypeEdited"
    DeliveryTypeDeleted = "DeliveryTypeDeleted"
    DeliveryCourierAdded = "DeliveryCourierAdded"
    DeliveryCourierEdited = "DeliveryCourierEdited"
    DeliveryCourierDeleted = "DeliveryCourierDeleted"
    PriceTypeAdded = "PriceTypeAdded"
    PriceTypeEdited = "PriceTypeEdited"
    PriceTypeDeleted = "PriceTypeDeleted"
    PaymentTypeAdded = "PaymentTypeAdded"
    PaymentTypeEdited = "PaymentTypeEdited"
    PaymentTypeDeleted = "PaymentTypeDeleted"
    AccountOperationCategoryAdded = "AccountOperationCategoryAdded"
    AccountOperationCategoryEdited = "AccountOperationCategoryEdited"
    AccountOperationCategoryDeleted = "AccountOperationCategoryDeleted"
    AccountAdded = "AccountAdded"
    AccountEdited = "AccountEdited"
    AccountDeleted = "AccountDeleted"
    CurrencyAdded = "CurrencyAdded"
    CurrencyEdited = "CurrencyEdited"
    CurrencyDeleted = "CurrencyDeleted"
    CurrencyExchangeRateEdited = "CurrencyExchangeRateEdited"
    TaxVatAdded = "TaxVatAdded"
    TaxVatEdited = "TaxVatEdited"
    TaxVatDeleted = "TaxVatDeleted"
    RegionAdded = "RegionAdded"
    RegionEdited = "RegionEdited"
    RegionDeleted = "RegionDeleted"
    DocContractAdded = "DocContractAdded"
    DocContractEdited = "DocContractEdited"
    DocContractDeleteMarked = "DocContractDeleteMarked"
    DocContractDeleted = "DocContractDeleted"
    DocPeriodClosingAdded = "DocPeriodClosingAdded"
    DocPeriodClosingEdited = "DocPeriodClosingEdited"
    DocPeriodClosingDeleted = "DocPeriodClosingDeleted"
    DocPeriodClosingCanceled = "DocPeriodClosingCanceled"
    DocSetPriceAdded = "DocSetPriceAdded"
    DocSetPriceEdited = "DocSetPriceEdited"
    DocSetPriceDeleteMarked = "DocSetPriceDeleteMarked"
    DocSetPriceDeleted = "DocSetPriceDeleted"
    DocSetPricePerformed = "DocSetPricePerformed"
    DocSetPricePerformCanceled = "DocSetPricePerformCanceled"
    DocInvoiceAdded = "DocInvoiceAdded"
    DocInvoiceEdited = "DocInvoiceEdited"
    DocInvoiceDeleteMarked = "DocInvoiceDeleteMarked"
    DocInvoiceDeleted = "DocInvoiceDeleted"
    DocInvoicePerformed = "DocInvoicePerformed"
    DocInvoicePerformCanceled = "DocInvoicePerformCanceled"
    DocTechMapAdded = "DocTechMapAdded"
    DocTechMapEdited = "DocTechMapEdited"
    DocTechMapDeleted = "DocTechMapDeleted"
    DocTechMapPerformed = "DocTechMapPerformed"
    DocTechMapPerformCanceled = "DocTechMapPerformCanceled"
    DocProductionAdded = "DocProductionAdded"
    DocProductionEdited = "DocProductionEdited"
    DocProductionDeleted = "DocProductionDeleted"
    DocProductionPerformed = "DocProductionPerformed"
    DocProductionPerformCanceled = "DocProductionPerformCanceled"
    FirmGroupAdded = "FirmGroupAdded"
    FirmGroupEdited = "FirmGroupEdited"
    FirmGroupDeleted = "FirmGroupDeleted"
    FirmAdded = "FirmAdded"
    FirmEdited = "FirmEdited"
    FirmDeleteMarked = "FirmDeleteMarked"
    FirmDeleted = "FirmDeleted"
    StockAdded = "StockAdded"
    StockEdited = "StockEdited"
    StockDeleteMarked = "StockDeleteMarked"
    StockDeleted = "StockDeleted"
    CashServerAdded = "CashServerAdded"
    CashServerEdited = "CashServerEdited"
    CashServerDeleted = "CashServerDeleted"
    CashServerSyncBegun = "CashServerSyncBegun"
    CashServerSyncEnded = "CashServerSyncEnded"
    OperatingCashAdded = "OperatingCashAdded"
    OperatingCashEdited = "OperatingCashEdited"
    OperatingCashDeleted = "OperatingCashDeleted"
    TargetAdded = "TargetAdded"
    TargetDeleted = "TargetDeleted"
    TargetFinished = "TargetFinished"
    DocOpeningBalanceAdded = "DocOpeningBalanceAdded"
    DocOpeningBalanceEdited = "DocOpeningBalanceEdited"
    DocOpeningBalanceDeleteMarked = "DocOpeningBalanceDeleteMarked"
    DocOpeningBalanceDeleted = "DocOpeningBalanceDeleted"
    DocOpeningBalancePerformed = "DocOpeningBalancePerformed"
    DocOpeningBalancePerformCanceled = "DocOpeningBalancePerformCanceled"
    ProjectAdded = "ProjectAdded"
    ProjectEdited = "ProjectEdited"
    ProjectDeleted = "ProjectDeleted"
    ProjectTaskAdded = "ProjectTaskAdded"
    ProjectTaskEdited = "ProjectTaskEdited"
    ProjectTaskDeleted = "ProjectTaskDeleted"
    ProjectTaskStatusSet = "ProjectTaskStatusSet"
    ProjectTaskResponsibleSet = "ProjectTaskResponsibleSet"
    ChatAdded = "ChatAdded"
    ChatEdited = "ChatEdited"
    ChatParticipantsSet = "ChatParticipantsSet"
    ChatParticipantsRemoved = "ChatParticipantsRemoved"
    ChatMessageAdded = "ChatMessageAdded"
    ChatMessageEdited = "ChatMessageEdited"
    ChatMessageDeleted = "ChatMessageDeleted"
    ChatMessageRead = "ChatMessageRead"
    ChatWriting = "ChatWriting"
    ChannelAdded = "ChannelAdded"
    ChannelEdited = "ChannelEdited"
    ChannelDeleted = "ChannelDeleted"
    LeadAdded = "LeadAdded"
    LeadEdited = "LeadEdited"
    LeadStageSet = "LeadStageSet"
    LeadResponsibleSet = "LeadResponsibleSet"
    LeadConverted = "LeadConverted"
    LeadClosed = "LeadClosed"
    DealAdded = "DealAdded"
    DealEdited = "DealEdited"
    DealStageSet = "DealStageSet"
    DealResponsibleSet = "DealResponsibleSet"
    DealClosed = "DealClosed"
    UserCheckedIn = "UserCheckedIn"
    UserCheckedOut = "UserCheckedOut"
    UserBreakStarted = "UserBreakStarted"
    UserBreakEnded = "UserBreakEnded"
    UserAvailabilityChanged = "UserAvailabilityChanged"
    LeadParticipantsSet = "LeadParticipantsSet"
    DealParticipantsSet = "DealParticipantsSet"
    ChatSuggest = "ChatSuggest"
    ChatMessagePinnedSet = "ChatMessagePinnedSet"
    ChatMessageReactionsSet = "ChatMessageReactionsSet"
    TicketAdded = "TicketAdded"
    TicketEdited = "TicketEdited"
    TicketResponsibleSet = "TicketResponsibleSet"
    TicketParticipantsSet = "TicketParticipantsSet"
    TicketClosed = "TicketClosed"
    ReportPrepared = "ReportPrepared"
    ReportError = "ReportError"
    TicketStatusSet = "TicketStatusSet"
    TicketSlaBreached = "TicketSlaBreached"
    TicketRatingSet = "TicketRatingSet"
    StorageCleanupProcessed = "StorageCleanupProcessed"
    ClientAdded = "ClientAdded"
    ClientEdited = "ClientEdited"
    ClientDeleted = "ClientDeleted"
    ClientResponsibleSet = "ClientResponsibleSet"
    ClientMerged = "ClientMerged"
    ChatMutedSet = "ChatMutedSet"
    ChatArchivedSet = "ChatArchivedSet"
    ChatPinnedSet = "ChatPinnedSet"
    ChatMessageCallback = "ChatMessageCallback"
    TicketClientSentimentSet = "TicketClientSentimentSet"


class WebHookStatusResponse(RegosModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    reputation_status: str | None = PydField(default=None, description="Текущий репутационный статус webhook URL с учётом blacklist.")
    blacklist_ttl_seconds: int | None = PydField(default=None, description="Оставшееся время нахождения в blacklist в секундах; null, если URL не находится в blacklist.")
    total_success: int | None = PydField(default=None, description="Общее количество успешных доставок.")
    total_fail: int | None = PydField(default=None, description="Общее количество неуспешных доставок.")
    last_error_message: str | None = PydField(default=None, description="Сообщение последней ошибки доставки (если была).")
    last_error_at: str | None = PydField(default=None, description="Дата и время последней ошибки доставки в UTC (если была)")


class WebHookStatusResponseRegosObjectResult(RegosModel):
    "OpenAPI-only typed equivalent of SingleObjectResult."
    model_config = ConfigDict(extra="ignore", populate_by_name=True)
    ok: bool | None = PydField(default=None, description="Признак успешности выполнения запроса.")
    result: WebHookStatusResponse | Error | None = PydField(default=None, description="Объект результата.")


# Imports are intentionally placed after model definitions to avoid circular imports.
from schemas.api.common.base import Error


WebhookGetResponse: TypeAlias = StringRegosArrayResult


_MODEL_NAMES = ['StringRegosArrayResult', 'WebHookStatusResponse', 'WebHookStatusResponseRegosObjectResult']


__all__ = [
    'StringRegosArrayResult',
    'WebHookActionsEnum',
    'WebHookStatusResponse',
    'WebHookStatusResponseRegosObjectResult',
    'WebhookGetResponse'
]
